/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SimpleObject } from "./components/my-component/my-component";
export namespace Components {
    interface MyComponent {
        "isActive": boolean;
        "items": any[];
        "name": string;
        "resetSelectionCount": () => Promise<void>;
        "selection": number;
        "selectionCount": number;
        "simpleObject": SimpleObject;
    }
    interface TestCheckbox {
        "isChecked": boolean;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLTestCheckboxElement extends Components.TestCheckbox, HTMLStencilElement {
    }
    var HTMLTestCheckboxElement: {
        prototype: HTMLTestCheckboxElement;
        new (): HTMLTestCheckboxElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "test-checkbox": HTMLTestCheckboxElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        "isActive"?: boolean;
        "items"?: any[];
        "name"?: string;
        "onButtonClick"?: (event: CustomEvent<any>) => void;
        "onValueChange"?: (event: CustomEvent<any>) => void;
        "selection"?: number;
        "selectionCount"?: number;
        "simpleObject"?: SimpleObject;
    }
    interface TestCheckbox {
        "isChecked"?: boolean;
        "onValueChange"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "test-checkbox": TestCheckbox;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "test-checkbox": LocalJSX.TestCheckbox & JSXBase.HTMLAttributes<HTMLTestCheckboxElement>;
        }
    }
}
