/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ButtonClicker {
    'callback': Function;
    'count': number;
    'type': string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface ScDatagrid {
    'getData': Function;
    'providedData': any[];
  }
  interface SlotExample {
    'innerFunction': Function;
  }
}

declare global {


  interface HTMLButtonClickerElement extends Components.ButtonClicker, HTMLStencilElement {}
  var HTMLButtonClickerElement: {
    prototype: HTMLButtonClickerElement;
    new (): HTMLButtonClickerElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLScDatagridElement extends Components.ScDatagrid, HTMLStencilElement {}
  var HTMLScDatagridElement: {
    prototype: HTMLScDatagridElement;
    new (): HTMLScDatagridElement;
  };

  interface HTMLSlotExampleElement extends Components.SlotExample, HTMLStencilElement {}
  var HTMLSlotExampleElement: {
    prototype: HTMLSlotExampleElement;
    new (): HTMLSlotExampleElement;
  };
  interface HTMLElementTagNameMap {
    'button-clicker': HTMLButtonClickerElement;
    'my-component': HTMLMyComponentElement;
    'sc-datagrid': HTMLScDatagridElement;
    'slot-example': HTMLSlotExampleElement;
  }
}

declare namespace LocalJSX {
  interface ButtonClicker {
    'callback'?: Function;
    'count'?: number;
    'onClickEvent'?: (event: CustomEvent<any>) => void;
    'type'?: string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface ScDatagrid {
    'getData'?: Function;
    'providedData'?: any[];
  }
  interface SlotExample {
    'innerFunction'?: Function;
  }

  interface IntrinsicElements {
    'button-clicker': ButtonClicker;
    'my-component': MyComponent;
    'sc-datagrid': ScDatagrid;
    'slot-example': SlotExample;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'button-clicker': LocalJSX.ButtonClicker & JSXBase.HTMLAttributes<HTMLButtonClickerElement>;
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'sc-datagrid': LocalJSX.ScDatagrid & JSXBase.HTMLAttributes<HTMLScDatagridElement>;
      'slot-example': LocalJSX.SlotExample & JSXBase.HTMLAttributes<HTMLSlotExampleElement>;
    }
  }
}


